#!/bin/bash

while true
do
  export POLE_CODE=1
  export POLE_MSG="X"


  OP=$(curl -s --max-time 1 http://192.168.1.243:8082/isup)
  RESP=$?
  if [ $RESP -ne 0 ]; then
    POLE_MSG="Server is DOWN (RC $RESP) Query failed."
  else 
    if [ ${#OP} -eq 0 ]; then
     POLE_MSG="Server is DOWN (Empty response!)"
    else
      OPJ=$(echo $OP | python3 -m json.tool | grep "ServerIsUp")
      if [ ${#OPJ} -eq 0 ]; then
        POLE_MSG="Server is DOWN (Cannot find ServerIsUp in response)"
    else
        POLE_CODE=0
        POLE_MSG="Server is UP"
      fi
    fi
  fi
  if [ $POLE_CODE -ne 0 ]; then
     echo "DOWN:"
     echo "$POLE_MSG"
  else 
     echo "UP:"
     echo "$POLE_MSG"
  fi

  echo "########################################################"
  sleep 5

done

