#!/bin/bash
CONTROL_DIR=$(realpath $(dirname "$0"))
echo "########################################################"
echo "Running in: $CONTROL_DIR"
cd $CONTROL_DIR

if [ x"${WebServerHome}" == "x" ]; then 
    echo "Value 'WebServerHome' is not assigned to a variable"
	exit 1
fi

if [ x"${WebServerPictures}" == "x" ]; then 
    echo "Value 'WebServerPictures' is not assigned to a variable"
    exit 1
fi

while true
do

  if [ $USER == stuart ]; then
    echo "Config file:goWebApp.json"
  ./goWebApp config=goWebApp.json -vr
  else
    echo "Config file:goWebAppPi.json"
  ./goWebApp config=goWebAppPi.json -vr
  fi
  
  RESP=$?
  echo "########################################################"
  echo "Response: $RESP"
  if [ $RESP -eq 11 ]; then
    echo "Server stopped"
    exit 1
  fi
  if [ $RESP -eq 10 ]; then
    echo "Server already running"
    exit 1
  fi
  if [ $RESP -eq 1 ]; then
    echo "Server error"
    exit 1
  fi
  echo "Server restarted"
done

