#!/bin/bash

echo "########################################################"
echo "Checking environment vars:"

if [ x"${WebServerRoot}" == "x" ]; then 
  echo "Value 'WebServerRoot' is not assigned to a variable"
  exit 1
fi
echo "WebServerRoot: $WebServerRoot"

if [ x"${WebServerData}" == "x" ]; then 
  echo "Value 'WebServerData' is not assigned to a variable"
	exit 1
fi
echo "WebServerData: $WebServerData"

if [ x"${WebServerHome}" == "x" ]; then 
  echo "Value 'WebServerHome' is not assigned to a variable"
	exit 1
fi
echo "WebServerHome: $WebServerHome"

if [ x"${WebServerPictures}" == "x" ]; then 
  echo "Value 'WebServerPictures' is not assigned to a variable"
  exit 1
fi
echo "WebServerPictures: $WebServerPictures"


echo "Checking Paths exist:"

if [ ! -d $WebServerRoot ]; then
  echo "Deploy dir '$WebServerRoot' has not been created"
  exit 1
fi

echo "WebServerRoot/exec: $WebServerRoot/exec"
if [ ! -d $WebServerRoot/exec ]; then
  echo "Deploy dir '$WebServerRoot/exec' has not been created"
  exit 1
fi

if [ ! -d $WebServerData ]; then
  echo "Deploy dir '$WebServerData' does not exist"
  exit 1
fi

if [ ! -d $WebServerHome ]; then
  echo "Deploy dir '$WebServerHome' does not exist"
  exit 1
fi

if [ ! -d $WebServerPictures ]; then
  echo "Deploy dir '$WebServerPictures' does not exist"
  exit 1
fi

cd $WebServerRoot
echo "########################################################"
echo "Running in: $WebServerRoot"

if [ ! -e $WebServerRoot/goWebApp ]; then
  echo "Exec file '$WebServerRoot/goWebApp' does not exist"
  exit 1
fi

if [ ! -e $WebServerRoot/exec/webtools ]; then
  echo "Exec file '$WebServerRoot/exec/webtools' does not exist"
  exit 1
fi

while true
do
  echo "Config file:goWebApp.json"
  ./goWebApp config=goWebApp.json -vr
  
  RESP=$?
  echo "########################################################"
  echo "Response: $RESP"
  if [ $RESP -eq 11 ]; then
    echo "Server stopped"
    exit 1
  fi
  if [ $RESP -eq 10 ]; then
    echo "Server already running"
    exit 1
  fi
  if [ $RESP -eq 1 ]; then
    echo "Server error"
    exit 1
  fi
  if [ $RESP -eq 127 ]; then
    echo "Server error"
    exit 1
  fi
  echo "Server restarted"
done

